#config.yaml
strategy:
  name: dodge  # Options: default, dodge, damage, aggressive
  parameters:
    reward_value: 1
    punishment_value: -0.5
    window_size: 10

input_features:
  include_image: true
  include_position: true  # Options: true or false
  position_type: "float"  # Options: "float" or "grid"
  include_player_charge: true
  include_enemy_charge: true
  temporal_charge: 20  # amount of previous frames for the charge state
  input_memory: 20  # number of previous inputs to include
  health_memory: 20  # number of previous health states to include
  include_player_chip: true  
  include_enemy_chip: true


